env:
  browser: true
  es2021: true
  node: true
extends:
  - love
  - plugin:react/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  'react/react-in-jsx-scope': 'off'
