env:
  browser: true
  es2021: true
  node: true
extends:
  - love
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
